### ISSUE TITLE
[ REFACTOR ] - 엔드 포인트 수정

### ISSUE THREAD

**Issue by nar0ng** [nar0ng/2024_BEOTKKOTTHON_TEAM_9_BE#12]
## 🛠️ 작업할 사항
작업할 사항에 대해 작성해주세요.
보호소 컨트롤러 관련 엔드포인트를 수정합니다.

## 📝 Todo-lists
- [ ] 보호견 리스트 조회
- [ ] 입양 현황 조회
- [ ] 입양 신청자 리스트 조회
- [ ] 입양 신청자 상세 정보 조회
