### ISSUE TITLE
[ REFACTOR ] - Shelter 관련 스웨거 설정

### ISSUE THREAD

**Issue by nar0ng** [nar0ng/2024_BEOTKKOTTHON_TEAM_9_BE#16]
## 🛠️ 작업할 사항
작업할 사항에 대해 작성해주세요.
shelter 관련하여 스웨거를 설정해줍니다.

## 📝 Todo-lists
- [ ] 보호견 리스트 조회
- [ ] 입양 현황 조회
- [ ] 입양 신청자 리스트 조회
- [ ] 입양 신청자 상세 정보 조회
