### ISSUE TITLE
[ FEAUTRE ] - 입양 신청서에 대한 승인 / 거절 API 구현

### ISSUE THREAD

**Issue by nar0ng** [nar0ng/2024_BEOTKKOTTHON_TEAM_9_BE#18]
## 🛠️ 작업할 사항
작업할 사항에 대해 작성해주세요.
공고에 대한 입양 신청서에 대해 상태를 승인 / 거절로 설정할 수 있는 API를 구현합니다.

## 📝 Todo-lists
- [x] 입양 신청서에 대한 상태에 대해 ENUM 값 등록
- [x] 공고의 상태에 대한 ENUM 값 등록
- [x] 입양 신청서의 상태를 설정할 수 있는 API
- [ ] 공고에 대한 입양 신청서의 상태가 하나라도 PASSED가 된다면 COMPLETED로 상태 변경
