### ISSUE TITLE
[ REFACTOR ] 입양 절차 질문 수정

### ISSUE THREAD

**Issue by nar0ng** [nar0ng/2024_BEOTKKOTTHON_TEAM_9_BE#2]
## 🛠️ 작업할 사항
작업할 사항에 대해 작성해주세요.
입양 절차 항목을 수정합니다.

## 📝 Todo-lists
- [x] 반려동물 키운 적 있습니까?
- [x] 현재 반려동물
- [x] 현재 함께 살고 있는 가족 구성원
- [x] 입양을 원하는 이유는
- [x] 입양 후 소식관리
